version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 1000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '1100:80'
    depends_on:
      - db
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 1200:7700
    environment:
      MEILI_MASTER_KEY: yourmasterkey

volumes:
  db_data:
